# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]
  release:
        types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x
    - name: Restore dependencies of project
      working-directory: ./source
      run: dotnet restore
    - name: Build project with no restore
      working-directory: ./source
      run: dotnet build --no-restore
    - name: CLI test for project
      working-directory: ./source
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: [ "build" ]
    if: github.event_name == "create"
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/Falcion/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      - run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
        working-directory: ./source
      - name: Publish the package to GPR
        run: dotnet nuget push bin/Release/*.nupkg
        working-directory: ./source
